#!/bin/sh

docker rm -f $(docker ps -a -f status=exited -q)
docker rmi $(docker images "aqueti/*" -q --no-trunc)

# load docker image
zcat /tmp/QWebServer-image*.tar.gz | docker load

user_name=$SUDO_USER
image_name=`docker images | grep aqueti | awk '{print$1,$2}' | sed 's# #:#g' | head -1`
sys_name=`cat /etc/aqueti/daemonConfiguration.json | awk '{for(i=1;i<=NF;i++){ if(match($i,/system/)){ if($(i+1)==":") print $(i+2); else print $(i+1) } } }' | sed 's/"//g' | sed 's/,//g'`

#if [ -z "${image_name}" ]; then
    COMMANDTOSTARTDOCKER="docker run --rm -p 5000:5000 -e AQUETI_SYSTEM_NAME=${sys_name} -v /etc/localtime:/etc/localtime:ro -v /var/tmp/aqueti:/var/tmp/aqueti -v /home/${user_name}/.ssh:/root/.ssh ${image_name}"

    HOMUNCULUSICON="#!/usr/bin/env xdg-open\n
    [Desktop Entry]\n
    Version=1.0\n
    Name=QWebServer\n
    Exec=$COMMANDTOSTARTDOCKER\n
    Icon=/etc/aqueti/icons/AquetiLogo.png\n
    Terminal=true\n
    Type=Application\n
    Categories=Development"
    HOMUNCULUSICONPATH="/home/${user_name}/Desktop/QWebServer.desktop"
    echo $HOMUNCULUSICON > $HOMUNCULUSICONPATH
    chown ${user_name}:${user_name} $HOMUNCULUSICONPATH
    chmod +x $HOMUNCULUSICONPATH
#fi

# delete temporary docker image file
rm /tmp/QWebServer-image*.tar.gz

exit 0
