#!/bin/sh

echo "postinst starting"

user_name=$SUDO_USER
image_name=`docker images | grep aqueti | awk '{print$1,$2}' | sed 's# #:#g' | head -1`
sys_name=`cat /etc/aqueti/daemonConfiguration.json | awk '{for(i=1;i<=NF;i++){ if(match($i,/system/)){ if($(i+1)==":") print $(i+2); else print $(i+1) } } }' | sed 's/"//g' | sed 's/,//g'`

docker rm $(docker stop $(docker ps -a | awk '{ print $1,$2 }' | grep aqueti | awk '{print $1 }'))
#docker rm -f $(docker ps -a -f status=exited -q)
docker rmi $(docker images "aqueti/*" -q --no-trunc)

# load docker image
zcat /tmp/QWebServer-image*.tar.gz | docker load

mkdir /etc/aqueti/homunculus
touch /etc/aqueti/homunculus/docker-compose.yml
echo "version: '3'
services:
  homunculus:
    image: aqueti/beta:2.0.6.0
    environment:
      - AQUETI_SYSTEM_NAME=${sys_name}
    ports:
      - 5000:5000
    volumes:
      - /var/log/aqueti:/var/log/supervisor
      - /var/tmp/aqueti:/var/tmp/aqueti
      - /etc/localtime:/etc/localtime
      - /home/${user_name}/.ssh:/root/.ssh
    restart: always" > /etc/aqueti/homunculus/docker-compose.yml

cp /tmp/homunculusd.service /etc/systemd/system
systemctl daemon-reload
systemctl enable homunculusd.service
service homunculusd start

cp /tmp/QView-0.1.0-x86_64.AppImage /opt/

# old stuff for creating desktop icon
QADMINICON="#!/usr/bin/env xdg-open\n
[Desktop Entry]\n
Version=1.0\n
Name=Launch_QAdmin\n
Icon=/etc/aqueti/icons/AquetiLogo.png\n
Terminal=false\n
URL=localhost:5000\n
Type=Link"
QADMINICONPATH="/home/${user_name}/Desktop/Launch_QAdmin.desktop"
echo $QVIEWICON > $QADMINICONPATH
chown ${user_name}:${user_name} $QADMINICONPATH
chmod +x $QADMINICONPATH

# delete temporary files
rm /tmp/QWebServer-image*.tar.gz /tmp/homunculusd.service /tmp/QView-0.1.0-x86_64.AppImage

echo "postinst finishing"

exit 0
