version: "3"
services:
  nginx:
    image: asis_nginx
    ports:
      - 80:80
      - 443:443
    container_name: nginx_container
    networks:
      - aqueti_net
    restart: on-failure
  asis:
    image: asis_asis
    container_name: asis_container
    networks:
      - aqueti_net
    restart: on-failure
    volumes:
      - /etc/aqueti/avi:/etc/aqueti/avi
      - /var/log/aqueti:/var/log/aqueti
      - /etc/localtime:/etc/localtime
      - /home/$USER/.ssh:/root/.ssh
  janus:
    image: asis_janus
    container_name: janus_container
    networks:
      - aqueti_net
    restart: on-failure
networks:
  aqueti_net:
    driver: bridge
